package lally;
// Generated 30 Dec, 2016 2:48:40 PM by Hibernate Tools 4.3.1



/**
 * Act generated by hbm2java
 */
public class Act  implements java.io.Serializable {


     private int id;
     private String pic;
     private String name;
     private String info;
     private String text;
     private Integer pic2;
     private Integer width;
     private Integer himg;
     private Integer wimg;

    public Act() {
    }

	
    public Act(int id) {
        this.id = id;
    }
    public Act(int id, String pic, String name, String info, String text, Integer pic2, Integer width, Integer himg, Integer wimg) {
       this.id = id;
       this.pic = pic;
       this.name = name;
       this.info = info;
       this.text = text;
       this.pic2 = pic2;
       this.width = width;
       this.himg = himg;
       this.wimg = wimg;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getPic() {
        return this.pic;
    }
    
    public void setPic(String pic) {
        this.pic = pic;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getInfo() {
        return this.info;
    }
    
    public void setInfo(String info) {
        this.info = info;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public Integer getPic2() {
        return this.pic2;
    }
    
    public void setPic2(Integer pic2) {
        this.pic2 = pic2;
    }
    public Integer getWidth() {
        return this.width;
    }
    
    public void setWidth(Integer width) {
        this.width = width;
    }
    public Integer getHimg() {
        return this.himg;
    }
    
    public void setHimg(Integer himg) {
        this.himg = himg;
    }
    public Integer getWimg() {
        return this.wimg;
    }
    
    public void setWimg(Integer wimg) {
        this.wimg = wimg;
    }




}


