package lally;
// Generated 30 Dec, 2016 2:48:40 PM by Hibernate Tools 4.3.1



/**
 * Am generated by hbm2java
 */
public class Am  implements java.io.Serializable {


     private int id2;
     private Menu menu;
     private String piclink;
     private String vidlink;
     private String text;
     private String rt;
     private String dir;
     private String wit;
     private String star;

    public Am() {
    }

	
    public Am(Menu menu) {
        this.menu = menu;
    }
    public Am(Menu menu, String piclink, String vidlink, String text, String rt, String dir, String wit, String star) {
       this.menu = menu;
       this.piclink = piclink;
       this.vidlink = vidlink;
       this.text = text;
       this.rt = rt;
       this.dir = dir;
       this.wit = wit;
       this.star = star;
    }
   
    public int getId2() {
        return this.id2;
    }
    
    public void setId2(int id2) {
        this.id2 = id2;
    }
    public Menu getMenu() {
        return this.menu;
    }
    
    public void setMenu(Menu menu) {
        this.menu = menu;
    }
    public String getPiclink() {
        return this.piclink;
    }
    
    public void setPiclink(String piclink) {
        this.piclink = piclink;
    }
    public String getVidlink() {
        return this.vidlink;
    }
    
    public void setVidlink(String vidlink) {
        this.vidlink = vidlink;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public String getRt() {
        return this.rt;
    }
    
    public void setRt(String rt) {
        this.rt = rt;
    }
    public String getDir() {
        return this.dir;
    }
    
    public void setDir(String dir) {
        this.dir = dir;
    }
    public String getWit() {
        return this.wit;
    }
    
    public void setWit(String wit) {
        this.wit = wit;
    }
    public String getStar() {
        return this.star;
    }
    
    public void setStar(String star) {
        this.star = star;
    }




}


