package lally;
// Generated 30 Dec, 2016 2:48:40 PM by Hibernate Tools 4.3.1



/**
 * Menu generated by hbm2java
 */
public class Menu  implements java.io.Serializable {


     private int id;
     private String menu;
     private Integer issubmenu;
     private String link;
     private String icon;
     private Am am;

    public Menu() {
    }

	
    public Menu(int id) {
        this.id = id;
    }
    public Menu(int id, String menu, Integer issubmenu, String link, String icon, Am am) {
       this.id = id;
       this.menu = menu;
       this.issubmenu = issubmenu;
       this.link = link;
       this.icon = icon;
       this.am = am;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getMenu() {
        return this.menu;
    }
    
    public void setMenu(String menu) {
        this.menu = menu;
    }
    public Integer getIssubmenu() {
        return this.issubmenu;
    }
    
    public void setIssubmenu(Integer issubmenu) {
        this.issubmenu = issubmenu;
    }
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }
    public String getIcon() {
        return this.icon;
    }
    
    public void setIcon(String icon) {
        this.icon = icon;
    }
    public Am getAm() {
        return this.am;
    }
    
    public void setAm(Am am) {
        this.am = am;
    }




}


